// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/aaliflowkitgrpc/aali-flowkit.proto

package aaliflowkitgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListFunctionsRequest is the input message for the ListFunctions method.
// As no input is required, this message is empty.
type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{0}
}

// ListFunctionsResponse is the output message for the ListFunctions method.
// It contains a map of function names to their definitions.
type ListFunctionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of function names to their definitions.
	Functions     map[string]*FunctionDefinition `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{1}
}

func (x *ListFunctionsResponse) GetFunctions() map[string]*FunctionDefinition {
	if x != nil {
		return x.Functions
	}
	return nil
}

// FunctionDefinition is the definition of an individual function.
// It contains the name, description, inputs and outputs of the function.
type FunctionDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the function.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Category of the function.
	Category string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	// Display name of the function;
	DisplayName string `protobuf:"bytes,4,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// List of input definitions for the function.
	Input []*FunctionInputDefinition `protobuf:"bytes,5,rep,name=input,proto3" json:"input,omitempty"`
	// List of output definitions for the function.
	Output        []*FunctionOutputDefinition `protobuf:"bytes,6,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FunctionDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FunctionDefinition) GetInput() []*FunctionInputDefinition {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *FunctionDefinition) GetOutput() []*FunctionOutputDefinition {
	if x != nil {
		return x.Output
	}
	return nil
}

// FunctionInputDefinition is the definition of an input for a function.
// It contains the name, type, Go language type and options for the input.
type FunctionInputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the input.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the input.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Go language type of the input.
	GoType string `protobuf:"bytes,3,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// List of options for the input, if applicable.
	Options       []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInputDefinition) Reset() {
	*x = FunctionInputDefinition{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInputDefinition) ProtoMessage() {}

func (x *FunctionInputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInputDefinition.ProtoReflect.Descriptor instead.
func (*FunctionInputDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionInputDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionInputDefinition) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionInputDefinition) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// FunctionOutputDefinition is the definition of an output for a function.
// It contains the name, type and Go language type of the output.
type FunctionOutputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the output.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type of the output.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Go language type of the output.
	GoType        string `protobuf:"bytes,3,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionOutputDefinition) Reset() {
	*x = FunctionOutputDefinition{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutputDefinition) ProtoMessage() {}

func (x *FunctionOutputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutputDefinition.ProtoReflect.Descriptor instead.
func (*FunctionOutputDefinition) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionOutputDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FunctionOutputDefinition) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

// FunctionInputs is the input message for the RunFunction method.
// It contains the name of the function to run and a list of inputs.
type FunctionInputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function to run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of inputs for the function.
	Inputs        []*FunctionInput `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInputs) Reset() {
	*x = FunctionInputs{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInputs) ProtoMessage() {}

func (x *FunctionInputs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInputs.ProtoReflect.Descriptor instead.
func (*FunctionInputs) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{5}
}

func (x *FunctionInputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInputs) GetInputs() []*FunctionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// Single input for a function.
type FunctionInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the input.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Go language type of the input.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Value of the input.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInput) Reset() {
	*x = FunctionInput{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInput) ProtoMessage() {}

func (x *FunctionInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInput.ProtoReflect.Descriptor instead.
func (*FunctionInput) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInput) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// FunctionOutputs is the output message for the RunFunction method.
// It contains the name of the function that was run and a list of outputs.
type FunctionOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the function that was run.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// List of outputs from the function.
	Outputs       []*FunctionOutput `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionOutputs) Reset() {
	*x = FunctionOutputs{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutputs) ProtoMessage() {}

func (x *FunctionOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutputs.ProtoReflect.Descriptor instead.
func (*FunctionOutputs) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionOutputs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutputs) GetOutputs() []*FunctionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// FunctionOutput is a single output from a function.
// It contains the name, Go language type and value of the output.
type FunctionOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the output.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Go language type of the output.
	GoType string `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	// Value of the output.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Code validation of the output. Only relevant for code generation.
	CodeValidation string `protobuf:"bytes,4,opt,name=code_validation,json=codeValidation,proto3" json:"code_validation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionOutput) Reset() {
	*x = FunctionOutput{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionOutput) ProtoMessage() {}

func (x *FunctionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionOutput.ProtoReflect.Descriptor instead.
func (*FunctionOutput) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionOutput) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *FunctionOutput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FunctionOutput) GetCodeValidation() string {
	if x != nil {
		return x.CodeValidation
	}
	return ""
}

// StreamOutput is the output message for the StreamFunction method.
// It contains the message counter, a flag indicating if this is the last message
type StreamOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Counter for the message in the stream.
	MessageCounter int32 `protobuf:"varint,1,opt,name=message_counter,json=messageCounter,proto3" json:"message_counter,omitempty"`
	// Indicates if this is the last message in the stream.
	IsLast bool `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	// Value of the output.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Code validation of the output. Only relevant for code generation.
	CodeValidation string `protobuf:"bytes,4,opt,name=code_validation,json=codeValidation,proto3" json:"code_validation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamOutput) Reset() {
	*x = StreamOutput{}
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutput) ProtoMessage() {}

func (x *StreamOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutput.ProtoReflect.Descriptor instead.
func (*StreamOutput) Descriptor() ([]byte, []int) {
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP(), []int{9}
}

func (x *StreamOutput) GetMessageCounter() int32 {
	if x != nil {
		return x.MessageCounter
	}
	return 0
}

func (x *StreamOutput) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *StreamOutput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StreamOutput) GetCodeValidation() string {
	if x != nil {
		return x.CodeValidation
	}
	return ""
}

var File_pkg_aaliflowkitgrpc_aali_flowkit_proto protoreflect.FileDescriptor

const file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDesc = "" +
	"\n" +
	"&pkg/aaliflowkitgrpc/aali-flowkit.proto\x12\x0faaliflowkitgrpc\"\x16\n" +
	"\x14ListFunctionsRequest\"\xcf\x01\n" +
	"\x15ListFunctionsResponse\x12S\n" +
	"\tfunctions\x18\x01 \x03(\v25.aaliflowkitgrpc.ListFunctionsResponse.FunctionsEntryR\tfunctions\x1aa\n" +
	"\x0eFunctionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.aaliflowkitgrpc.FunctionDefinitionR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12 \n" +
	"\vdisplayName\x18\x04 \x01(\tR\vdisplayName\x12>\n" +
	"\x05input\x18\x05 \x03(\v2(.aaliflowkitgrpc.FunctionInputDefinitionR\x05input\x12A\n" +
	"\x06output\x18\x06 \x03(\v2).aaliflowkitgrpc.FunctionOutputDefinitionR\x06output\"t\n" +
	"\x17FunctionInputDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ago_type\x18\x03 \x01(\tR\x06goType\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"[\n" +
	"\x18FunctionOutputDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\ago_type\x18\x03 \x01(\tR\x06goType\"\\\n" +
	"\x0eFunctionInputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x06inputs\x18\x02 \x03(\v2\x1e.aaliflowkitgrpc.FunctionInputR\x06inputs\"R\n" +
	"\rFunctionInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"`\n" +
	"\x0fFunctionOutputs\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1f.aaliflowkitgrpc.FunctionOutputR\aoutputs\"|\n" +
	"\x0eFunctionOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12'\n" +
	"\x0fcode_validation\x18\x04 \x01(\tR\x0ecodeValidation\"\x8f\x01\n" +
	"\fStreamOutput\x12'\n" +
	"\x0fmessage_counter\x18\x01 \x01(\x05R\x0emessageCounter\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12'\n" +
	"\x0fcode_validation\x18\x04 \x01(\tR\x0ecodeValidation2\x9f\x02\n" +
	"\x11ExternalFunctions\x12`\n" +
	"\rListFunctions\x12%.aaliflowkitgrpc.ListFunctionsRequest\x1a&.aaliflowkitgrpc.ListFunctionsResponse\"\x00\x12R\n" +
	"\vRunFunction\x12\x1f.aaliflowkitgrpc.FunctionInputs\x1a .aaliflowkitgrpc.FunctionOutputs\"\x00\x12T\n" +
	"\x0eStreamFunction\x12\x1f.aaliflowkitgrpc.FunctionInputs\x1a\x1d.aaliflowkitgrpc.StreamOutput\"\x000\x01B\x13Z\x11./aaliflowkitgrpcb\x06proto3"

var (
	file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescOnce sync.Once
	file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescData []byte
)

func file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescGZIP() []byte {
	file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescOnce.Do(func() {
		file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDesc), len(file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDesc)))
	})
	return file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDescData
}

var file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_aaliflowkitgrpc_aali_flowkit_proto_goTypes = []any{
	(*ListFunctionsRequest)(nil),     // 0: aaliflowkitgrpc.ListFunctionsRequest
	(*ListFunctionsResponse)(nil),    // 1: aaliflowkitgrpc.ListFunctionsResponse
	(*FunctionDefinition)(nil),       // 2: aaliflowkitgrpc.FunctionDefinition
	(*FunctionInputDefinition)(nil),  // 3: aaliflowkitgrpc.FunctionInputDefinition
	(*FunctionOutputDefinition)(nil), // 4: aaliflowkitgrpc.FunctionOutputDefinition
	(*FunctionInputs)(nil),           // 5: aaliflowkitgrpc.FunctionInputs
	(*FunctionInput)(nil),            // 6: aaliflowkitgrpc.FunctionInput
	(*FunctionOutputs)(nil),          // 7: aaliflowkitgrpc.FunctionOutputs
	(*FunctionOutput)(nil),           // 8: aaliflowkitgrpc.FunctionOutput
	(*StreamOutput)(nil),             // 9: aaliflowkitgrpc.StreamOutput
	nil,                              // 10: aaliflowkitgrpc.ListFunctionsResponse.FunctionsEntry
}
var file_pkg_aaliflowkitgrpc_aali_flowkit_proto_depIdxs = []int32{
	10, // 0: aaliflowkitgrpc.ListFunctionsResponse.functions:type_name -> aaliflowkitgrpc.ListFunctionsResponse.FunctionsEntry
	3,  // 1: aaliflowkitgrpc.FunctionDefinition.input:type_name -> aaliflowkitgrpc.FunctionInputDefinition
	4,  // 2: aaliflowkitgrpc.FunctionDefinition.output:type_name -> aaliflowkitgrpc.FunctionOutputDefinition
	6,  // 3: aaliflowkitgrpc.FunctionInputs.inputs:type_name -> aaliflowkitgrpc.FunctionInput
	8,  // 4: aaliflowkitgrpc.FunctionOutputs.outputs:type_name -> aaliflowkitgrpc.FunctionOutput
	2,  // 5: aaliflowkitgrpc.ListFunctionsResponse.FunctionsEntry.value:type_name -> aaliflowkitgrpc.FunctionDefinition
	0,  // 6: aaliflowkitgrpc.ExternalFunctions.ListFunctions:input_type -> aaliflowkitgrpc.ListFunctionsRequest
	5,  // 7: aaliflowkitgrpc.ExternalFunctions.RunFunction:input_type -> aaliflowkitgrpc.FunctionInputs
	5,  // 8: aaliflowkitgrpc.ExternalFunctions.StreamFunction:input_type -> aaliflowkitgrpc.FunctionInputs
	1,  // 9: aaliflowkitgrpc.ExternalFunctions.ListFunctions:output_type -> aaliflowkitgrpc.ListFunctionsResponse
	7,  // 10: aaliflowkitgrpc.ExternalFunctions.RunFunction:output_type -> aaliflowkitgrpc.FunctionOutputs
	9,  // 11: aaliflowkitgrpc.ExternalFunctions.StreamFunction:output_type -> aaliflowkitgrpc.StreamOutput
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_aaliflowkitgrpc_aali_flowkit_proto_init() }
func file_pkg_aaliflowkitgrpc_aali_flowkit_proto_init() {
	if File_pkg_aaliflowkitgrpc_aali_flowkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDesc), len(file_pkg_aaliflowkitgrpc_aali_flowkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_aaliflowkitgrpc_aali_flowkit_proto_goTypes,
		DependencyIndexes: file_pkg_aaliflowkitgrpc_aali_flowkit_proto_depIdxs,
		MessageInfos:      file_pkg_aaliflowkitgrpc_aali_flowkit_proto_msgTypes,
	}.Build()
	File_pkg_aaliflowkitgrpc_aali_flowkit_proto = out.File
	file_pkg_aaliflowkitgrpc_aali_flowkit_proto_goTypes = nil
	file_pkg_aaliflowkitgrpc_aali_flowkit_proto_depIdxs = nil
}
